### ISSUE TITLE
Some attacks can be spammed and the other player cannot defend - easy win:)

### ISSUE THREAD

**Issue by Sandruski** [AngryFrogDev/Dungeon-Brawler#36]
### What priority level does this issue have?
_(A - Severe, Crash; B - Important, Gameplay Affected; C - Cosmetic, Polish)_
B (Gameplay Affected)

---
### What is the expected behaviour?
Attacks should have a cooldown or something.

---
### What is the actual behaviour shown?
I can perform the fireball attack and keep doing it and the other player will die without being able to defend.

---
### Indicate us the steps to reproduce said behaviour:
Spam fireballs.

**Comment by t3m1X** [comment]
Has been fixed in Alpha release.
