### ISSUE TITLE
mana bug

### ISSUE THREAD

**Issue by morgadoCV** [AngryFrogDev/Dungeon-Brawler#42]
### What priority level does this issue have?
_(A - Severe, Crash; B - Important, Gameplay Affected; C - Cosmetic, Polish)_

B

---
### What is the expected behaviour?
Mana should only refund when you hit an enemy

---
### What is the actual behaviour shown?
mana refills always, and the mage refills it's mana using habilities
---
### Indicate us the steps to reproduce said behaviour:
use your attacks

**Comment by t3m1X** [comment]
This has been fixed in the Alpha release of the game.
