### ISSUE TITLE
Players animations on rematch menu

### ISSUE THREAD

**Issue by JoanValiente** [AngryFrogDev/Dungeon-Brawler#43]
### What priority level does this issue have?
_(A - Severe, Crash; B - Important, Gameplay Affected; C - Cosmetic, Polish)_
C

---
### What is the expected behaviour?
Normal animation.

---
### What is the actual behaviour shown?
The animation gets buged when the game ends. (On the rematch menu).

---

**Comment by t3m1X** [comment]
Duplicate of #37
