### ISSUE TITLE
Mage get stucked

### ISSUE THREAD

**Issue by DavidTheMaaster** [AngryFrogDev/Dungeon-Brawler#54]
### What priority level does this issue have?
_(A - Severe, Crash; B - Important, Gameplay Affected; C - Cosmetic, Polish)_

B
---
### What is the expected behaviour?

---
### What is the actual behaviour shown?

If you press RB + Left the mage just get stucked 

![captura 2](https://user-images.githubusercontent.com/26002028/39699500-c7b73250-51f9-11e8-919d-3d564b58cd3c.PNG)

---

**Comment by t3m1X** [comment]
Duplicate of #52
