### ISSUE TITLE
Player cant choose between warrior and mage

### ISSUE THREAD

**Issue by Wilhelman** [AngryFrogDev/Dungeon-Brawler#56]
### What priority level does this issue have?
_(A - Severe, Crash; B - Important, Gameplay Affected; C - Cosmetic, Polish)_
b

---
### What is the expected behaviour?
to choose one heroe

---
### What is the actual behaviour shown?
we cant choose

---
### Indicate us the steps to reproduce said behaviour:
go to one vs one

**Comment by t3m1X** [comment]
Cannot seem to replicate on Alpha release.
