### ISSUE TITLE
Mana doesn't count down

### ISSUE THREAD

**Issue by lFreecss** [AngryFrogDev/Dungeon-Brawler#59]
### What priority level does this issue have?
_(A - Severe, Crash; B - Important, Gameplay Affected; C - Cosmetic, Polish)_
B - Important, Gameplay Affected

---
### What is the expected behaviour?
If any player spam abilites their mana bar runs out

---
### What is the actual behaviour shown?
The player can win spamming

---
### Indicate us the steps to reproduce said behaviour:
Start the game, spam abilites.

**Comment by t3m1X** [comment]
Merging with #36
