### ISSUE TITLE
Warrior is inmune to the mage's fireballs when performing a circular attack

### ISSUE THREAD

**Issue by ValdiviaDev** [AngryFrogDev/Dungeon-Brawler#61]
### What priority level does this issue have?
_(A - Severe, Crash; B - Important, Gameplay Affected; C - Cosmetic, Polish)_
B

---
### What is the expected behaviour?
Not being inmune.

---
### What is the actual behaviour shown?
Benig inmune.

---
### Indicate us the steps to reproduce said behaviour:
Make a circular attack while mage is throwing you fireballs.

**Comment by t3m1X** [comment]
This is the intended behaviour of the warrior spinning attack (avoiding projectiles).
