### ISSUE TITLE
Animation error

### ISSUE THREAD

**Issue by Scarzard** [AngryFrogDev/Dungeon-Brawler#90]
### What priority level does this issue have?
_(A - Severe, Crash; B - Important, Gameplay Affected; C - Cosmetic, Polish)_
B

---
### What is the expected behaviour?
Grassus' sword hit box should be as long as the its animation.

---
### What is the actual behaviour shown?
Grassus' sword hit box is shorter than the animation.

---
### Indicate us the steps to reproduce said behaviour:
Grassus light attack.

**Comment by t3m1X** [comment]
This was due to balancing
