### ISSUE TITLE
Should be able to play both with joystick or d-pad.

### ISSUE THREAD

**Issue by dynamiczero99** [AngryFrogDev/Dungeon-Brawler#92]
### What priority level does this issue have?
_(A - Severe, Crash; B - Important, Gameplay Affected; C - Cosmetic, Polish)_
B

---
### What is the expected behaviour?
Players should be able to choose to play with joystick or d-pad.

---
### What is the actual behaviour shown?
You can only move with the joystick.

---
### Indicate us the steps to reproduce said behaviour:
---

**Comment by t3m1X** [comment]
Already implemented
